feat(components): inclui componente de Header para navegação de páginas
graysoncunha/carango-bom-base pull request #6
Opened 2021-08-18 21:44 UTC by graysoncunha

![image](https://user-images.githubusercontent.com/7623438/129976209-e3c204a8-8441-4fdd-8c12-89c23bdeb256.png)

[Tutorial seguido](https://betterprogramming.pub/building-a-basic-header-with-materialui-and-react-js-d650f75b4b0a)

2021-08-18 21:44 UTC, graysoncunha commented
![](https://github.trello.services/images/mini-trello-icon.png) [[app] Criar menu de acesso as páginas](https://trello.com/c/efZUxGi7/23-app-criar-menu-de-acesso-as-p%C3%A1ginas)

2021-08-20 13:35 UTC, LauraB06 requested changes
O que você acha de fazer os testes pra essa parte do menu de navegação? A gente pode checar a partir do path do navegador.

2021-08-21 15:27 UTC, knuxbbs approved these changes

2021-08-23 13:59 UTC, LauraB06 approved these changes

2021-08-23 13:59 UTC, merged